spring.datasource.url=jdbc:postgresql://db.wpnotthptzpggyqxduft.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=leading-anteater-289990.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAABGzGAAIgcDFiYzA3ZmQ1MWUzMzU0Njk4YjllNTRhZDI2MzQzZmU3YQ
spring.data.redis.ssl.enabled=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiry-ms=86400000

supabase.url=https://wpnotthptzpggyqxduft.supabase.co
supabase.key=${SUPABASE_SERVICE_KEY}
